# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache Maven Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - name: Set up Maven Settings
      uses: s4u/maven-settings-action@v2.4.0
      with:
        servers: |
          <server>
            <id>mule-enterprise</id>
            <username>${{ secrets.mule_nexus_username }}</username>
            <password>${{ secrets.mule_nexus_password }}</password>
          </server>

    - name: Print effective-settings (optional)
      run: mvn help:effective-settings

    - name: Build with Maven
      run: mvn -B package -f pom.xml

    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(echo $artifactName1 | sed "s/.jar/-$commitHash.jar/")
        mv $artifactName1 $artifactName2

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: target/*.jar

